---

env: 
  global:
    - CC_TEST_REPORTER_ID=21ea36cff7f1abaebb3fe6486ffb0fbc97dec145a490b531fd09944af4642257

language: node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - ../medium-transactional-typeorm/scripts/before_script.sh

script:
  - yarn lint
  - yarn typecheck
  - yarn test:coverage
  
after_script:
  - ../medium-transactional-typeorm/scripts/after_script.sh