version: "3"
services:
  postgres:
    image: postgres:13.4
    container_name: db_postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password